name: learn-github-actions
env:
  ID_RSA: ${{ vars.ID_RSA}}
  SERVER_USER: ${{ vars.SERVER_USER }}
  SERVER_IP: ${{ vars.SERVER_IP }}

run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Use variables
        env:
          SSH_KEY: /tmp/ssh_agent.sock
        run: |
          echo "ID_RSA variable : $ID_RSA"
          echo "SERVER_USER variable : $SERVER_USER"
          echo "SERVER_IP variable : $SERVER_IP"
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ vars.ID_RSA}}"
          ssh -i $SSH_KEY -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "ls"
