name: learn-github-actions
env:
  ID_RSA: ${{ vars.ID_RSA}}
  SERVER_USER: ${{ vars.SERVER_USER }}
  SERVER_IP: ${{ vars.SERVER_IP }}

run-name: ${{ github.actor }} CICD
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy - Down
        run: |
          sudo docker compose down

      - name: Deploy - Build
        run: |
          sudo docker compose build

  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy - up
        run: |
          sudo docker compose up -d
