name: learn-github-actions
env:
  ID_RSA: ${{ vars.ID_RSA}}
  SERVER_USER: ${{ vars.SERVER_USER }}
  SERVER_IP: ${{ vars.SERVER_IP }}

run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      - name: Show variables
        env:
          SSH_KEY: id_rsa
        run: |
          echo "ID_RSA variable : $ID_RSA"
          echo "SERVER_USER variable : $SERVER_USER"
          echo "SERVER_IP variable : $SERVER_IP"
          echo ls -a
          echo "$ID_RSA" > $SSH_KEY
          echo sudo chmod 600 $SSH_KEY
          ls -a
