name: learn-github-actions
env:
  ID_RSA: ${{ vars.ID_RSA}}
  SERVER_USER: ${{ vars.SERVER_USER }}
  SERVER_IP: ${{ vars.SERVER_IP }}

run-name: ${{ github.actor }} CICD
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Build
      #   run: |
      #     sudo docker compose build

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: |
          sudo docker compose down
          sudo docker compose up -d
