name: learn-github-actions
env:
  ID_RSA: ${{ vars.ID_RSA}}
  SERVER_USER: ${{ vars.SERVER_USER }}
  SERVER_IP: ${{ vars.SERVER_IP }}

run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Deploy - Down
        run: |
          docker compose down

      - name: Deploy - Build
        run: |
          docker compose build

      - name: Deploy - up
        run: |
          docker compose up -d
